shadowsocks/shadowsocks-rust

- src/relay/tcprelay/local.rs
I don't know why this should be added, but it works.
> close client connections on error

- src/config.rs
- src/crypto/cipher.rs
- src/crypto/openssl.rs
- src/crypto/table.rs
- src/relay/socks5.rs
- src/relay/tcprelay/server.rs
- src/relay/udprelay/local.rs
- src/relay/udprelay/server.rs
When I was creating a fork with a minimal set of functionalities that I actually use, I could not help but notice some potential refinements. This pull request addresses some of them.
Please refer to the commit messages for more information.
> Code cleanup

- src/relay/dns_resolver.rs
https://github.com/shadowsocks/shadowsocks-rust/issues/118 关联
> fix dns resolve error

- README.md
> Tips for ssdns

- Cargo.toml
- src/bin/tunnel.rs
- src/config.rs
- src/relay/tcprelay/socks5_local.rs
It can be used to benchmark.
Usage:
sstunnel -v -s 127.0.0.1:8488 -m plain -k password -b 127.0.0.1:1090 -f 127.0.0.1:5201
"-f xxx" : the target/forwad address xxx
> Add a tunnel app

- src/crypto/aead.rs
reduce loops and type conversions
> reduce loops and type conversions

- Cargo.toml
- src/bin/local.rs
- src/bin/server.rs
- src/bin/tunnel.rs
- src/config.rs
- src/relay/tcprelay/server.rs
- src/relay/tcprelay/utils.rs
- src/relay/utils.rs
> ssserver supports binding local address for connecting remote

- Cargo.toml
- src/acl/mod.rs
- src/bin/local.rs
- src/config.rs
- src/relay/sys/unix/mod.rs
- src/relay/sys/windows/mod.rs
- src/relay/tcprelay/proxy_stream.rs
- src/relay/udprelay/socks5_local.rs
- src/relay/utils.rs
This PR added:
1. Protect socket logic for Android.
2. Misc fixes for Android VPNService.
I think some rework and cleanup are still needed, especially for the interfaces.
> Multiple changes for shadowsocks-android

- Cargo.toml
- src/bin/local.rs
- src/config.rs
- src/context.rs
- src/relay/dnsrelay/mod.rs
- src/relay/local.rs
- src/relay/mod.rs
- src/relay/sys/unix/mod.rs
It maybe also useful for `ssredir` and `sslocal`.
> Add DNS relay for Android

- .gitignore
- Cargo.toml
- src/bin/local.rs
- src/config.rs
- src/context.rs
- src/relay/dnsrelay/mod.rs
- src/relay/local.rs
- src/relay/mod.rs
- src/relay/sys/unix/mod.rs
- src/relay/tcprelay/sys/unix/linux.rs
https://github.com/shadowsocks/shadowsocks-android/pull/2454
ACL (domain name) works now.
> Add DNS relay for Android (Part 2)

- src/bin/local.rs
- src/bin/manager.rs
- src/bin/redir.rs
- src/bin/server.rs
- src/bin/tunnel.rs
- src/config.rs
- src/context.rs
- src/crypto/cipher.rs
- src/relay/dnsrelay/mod.rs
- src/relay/mod.rs
- src/relay/socks5.rs
Optimized code structure and improvements
> Local dns relay socks5 query with client

- src/bin/local.rs
- src/bin/manager.rs
- src/bin/redir.rs
- src/bin/server.rs
- src/bin/ssurl.rs
- src/bin/tunnel.rs
> CLAP: Simple parameter configuration replaced with macro expressions

- src/bin/local.rs
- src/bin/manager.rs
- src/bin/redir.rs
- src/bin/server.rs
- src/bin/ssurl.rs
- src/bin/tunnel.rs
Reverts shadowsocks/shadowsocks-rust#219
> Revert "CLAP: Simple parameter configuration replaced with macro expressions"

- src/relay/dnsrelay/mod.rs
- src/relay/dnsrelay/upstream.rs
I tried integrating `trust-dns-server`, it turns out that using it will block the entire thread (it takes a `&Runtime` as input). To be fair, I suspect there is anything we can really use from trust-dns besides `trust-dns-proto`.
P.S. This TCP server closes connection for every query. This should not be an issue as the relay should run locally.
> Let DNS relay run on TCP as well

- src/config.rs
- src/relay/udprelay/redir_local.rs
- src/relay/udprelay/server.rs
- src/relay/udprelay/socks5_local.rs
- src/relay/udprelay/tunnel_local.rs
https://github.com/shadowsocks/shadowsocks-rust/issues/252
> Add option for max number of UDP associations

- src/relay/dnsrelay/mod.rs
Added additional data examination for MX and NS records as per RFC. Probably will not be useful ever. Untested.
> Refine support for MX and NS records in DNS relay

- src/relay/dns_resolver/tokio_dns_resolver.rs
> Warn when using tokio DNS resolver

- src/relay/udprelay/server.rs
1. I think there is no need to be actively waking up and closing UDP connections.
2. More robust against IPv4-mapped IPv6 addresses.
> Refine udprelay

- src/relay/dnsrelay/upstream.rs
- src/relay/loadbalancing/server.rs
- src/relay/udprelay/association.rs
- src/relay/udprelay/client.rs
> Connect UDP sockets

- .github/workflows/build-release.yml
- Cargo.toml
- build/Dockerfile.mips-unknown-linux-musl
- build/Dockerfile.mipsel-unknown-linux-musl
- build/build-release
- src/crypto/aead.rs
- src/crypto/cipher.rs
- src/crypto/mod.rs
- src/relay/manager.rs
I will finish build script soon, maybe...
> Add support for MIPS

- src/relay/udprelay/client.rs
Adds split support to the client that allows concurrent access to the splited halves from different tasks.
> Add split support to the UDP client

- Cargo.toml
Reverts shadowsocks/shadowsocks-rust#342
> Revert "minimize target file in size"

- README.md
> Add Docker image usage guide

- snap/snapcraft.yaml
> Adding Snapcraft

- README.md
and add: Snapcraft / archlinuxcn
> rearrange README.md badges

- .github/workflows/build-release.yml
> ci: Fix build release

- Cargo.toml
- README.md
- bin/common/mod.rs
- bin/sslocal.rs
- bin/ssmanager.rs
- bin/ssserver.rs
- configs/genipset.py
- crates/shadowsocks-service/Cargo.toml
- crates/shadowsocks-service/src/acl/mod.rs
- crates/shadowsocks-service/src/local/dns/upstream.rs
- crates/shadowsocks-service/src/local/http/dispatcher.rs
- crates/shadowsocks-service/src/local/http/http_stream.rs
- crates/shadowsocks-service/src/local/net/udp/association.rs
- crates/shadowsocks-service/src/local/redir/server.rs
- crates/shadowsocks-service/src/local/socks/server/mod.rs
- crates/shadowsocks-service/src/local/socks/server/socks5/udprelay.rs
- crates/shadowsocks-service/src/local/socks/socks4.rs
- crates/shadowsocks-service/src/local/tun/udp.rs
- crates/shadowsocks-service/src/local/tunnel/server.rs
- crates/shadowsocks-service/src/local/tunnel/udprelay.rs
- crates/shadowsocks-service/src/server/server.rs
- crates/shadowsocks-service/src/server/tcprelay.rs
- crates/shadowsocks-service/src/server/udprelay.rs
- crates/shadowsocks/Cargo.toml
- crates/shadowsocks/src/dns_resolver/resolver.rs
- crates/shadowsocks/src/manager/protocol.rs
- crates/shadowsocks/src/net/option.rs
- crates/shadowsocks/src/net/sys/unix/uds.rs
- debian/changelog
- debian/control
commits marked with `*` means that they involve changes in the code.
> Fix spelling

- Cargo.lock
- crates/shadowsocks-service/Cargo.toml
- crates/shadowsocks-service/src/acl/mod.rs
> ACL regex rules convert to tree-rules or set-rules

- Cargo.lock
- Cargo.toml
- crates/shadowsocks/Cargo.toml
- crates/shadowsocks/src/relay/udprelay/proxy_socket.rs
> fixed UDP listener binds to dual-stack addresses (::)

- crates/shadowsocks-service/src/local/net/udp/association.rs
sorry the pr #714 missed await when commit , this pr is just fix it.
> fixed pr #714

- build/build-release
compress the new added ssservice for mips targets.
> Compress ssservice for mips targets

- README.md
- k8s/chart/values.yaml
- k8s/shadowsocks-rust.yaml
Sorry for the last PR. I forgot to change the default docker image after local testing.
> chore(k8s): change default image to ghcr latest

- .github/workflows/build-release.yml
add popular armv7 build targets
> Update build-release.yml to add popular armv7 build targets

- README.md
Reference: https://github.com/shadowsocks/shadowsocks-rust/issues/830
> fix(docs): JSON config usage update

- .github/workflows/build-nightly-release.yml
- .github/workflows/build-release.yml
- build/build-release
- build/build-release-zigbuild
1. Fix the UPX compression issue in GitHub Actions. 
2. Use upx --lzma --best instead of upx -9 to get a better compression ratio.
> Fix UPX compression issue.

- Dockerfile
- README.md
- Update base image to alpine 3.17
> Update docker base image

- .github/workflows/build-nightly-release.yml
- .github/workflows/build-release.yml
- build/build-release
- build/build-release-zigbuild
Reverts shadowsocks/shadowsocks-rust#1123
Related to: shadowsocks/shadowsocks-rust#1145
> Revert "Fix UPX compression issue."

- README.md
> add HowTo install via snap

- README.md
* Add notice about obsolete link to wiki configuration, 
* Add note about snapd configuration file path.
> Update Configuration part of README.md

- crates/shadowsocks/src/net/sys/unix/others.rs
> fix(shadowsocks): unbreak OpenBSD build

- build/build-host-release.ps1
> Fix: release script failed to pack sswinservice.exe

- debian/config.json
- debian/shadowsocks-rust.postinst
Fixes https://github.com/shadowsocks/shadowsocks-rust/issues/1700
> Remove dependency on pwgen

- crates/shadowsocks/src/net/sys/unix/bsd/freebsd.rs
Fix freebsd build error reported at https://github.com/shadowsocks/shadowsocks-org/issues/279 .
> fix freebsd build error

- crates/shadowsocks/src/relay/udprelay/proxy_socket.rs
Fix clippy warnings that shows up in https://github.com/shadowsocks/shadowsocks-rust/pull/1887/files.
> chore: clippy fix

- .github/workflows/build-msrv.yml
- .vscode/settings.json
- Cargo.lock
- Cargo.toml
- crates/shadowsocks-service/Cargo.toml
Replace #1851 for fixing msrv. Ref: https://github.com/JulianSchmid/etherparse/issues/116
> fix(deps): update rust crate etherparse to 0.17

- .github/workflows/build-msrv.yml
- .github/workflows/build-nightly-release.yml
- .github/workflows/build-release.yml
- deny.toml
The latest github actions ci `build-msrv-shadowsocks-rust (ubuntu-latest)` failed with "No space left on device".
https://github.com/shadowsocks/shadowsocks-rust/actions/runs/13928656588/job/38979838866
> chore: free ubuntu-latest spaces

- crates/shadowsocks/src/net/sys/unix/bsd/freebsd.rs
- crates/shadowsocks/src/net/sys/unix/bsd/macos.rs
- crates/shadowsocks/src/net/sys/unix/linux/mod.rs
- crates/shadowsocks/src/net/sys/unix/others.rs
- crates/shadowsocks/src/net/sys/windows/mod.rs
> Apply outbound_bind_addr to UDP traffic in ssserver

- crates/shadowsocks-service/src/local/dns/server.rs
Fixes https://github.com/shadowsocks/shadowsocks-android/issues/3185.
> fix: domain name comparison in should_forward_by_query
