- src/bin/local.rs
systemd 之类的程序需要在失败时返回表示失败的状态码。
> panic on failure for sslocal

- src/bin/local.rs
- src/bin/server.rs
This pull request fixes a regression initially described in Issue #19 and fixed in c5822d9ab5740414d317da95f1fe6d75c92ab3c4 by increasing the default stack size to 128K. The bug was reintroduced in cff29c3f226183a0963eb4d7a358423433f72ca5, where ``COROUTINE_STACK_SIZE`` was removed from [src/relay/mod.rs](https://github.com/zonyitoo/shadowsocks-rust/commit/cff29c3f226183a0963eb4d7a358423433f72ca5#diff-c8cd9e7fad78336b2736f91937ce4102L40) and ``default_stack_size`` was set to 64K in [src/bin/local.rs](https://github.com/zonyitoo/shadowsocks-rust/commit/cff29c3f226183a0963eb4d7a358423433f72ca5#diff-bff3171e8f58772ecdd6d044b736927eR278) and [src/bin/local.rs](https://github.com/zonyitoo/shadowsocks-rust/commit/cff29c3f226183a0963eb4d7a358423433f72ca5#diff-c110e1433afdc14adcd9cda130d53415R258) …
> Increase the default stack size from 64K to 128K

- Cargo.toml
- src/relay/socks5.rs
The rationale of this pull request is similar to that of [pull request #40](https://github.com/BurntSushi/byteorder/pull/40) of ``byteorder``. Before ``byteorder`` 0.5.x, we need to handle two (syntactically) different yet (conceptually) equivalent versions of errors (i.e., ``std::io::Error`` and ``byteorder::Error``). With ``byteorder`` 0.5.x, we can write much neater code.
> Update dependency ``byteorder`` from 0.3.x to 0.5.x

- src/relay/dns_resolver.rs
some case, `.parse::<DNameBuf>()` may fail. such as `.disqus.com`.
> fix parse DNameBuf panic

- src/monitor.rs
so that the manager / supervisor knows that we're exiting successfully.
> exit with 0 on SIGTERM / SIGINT

- debian/changelog
- debian/control
- debian/copyright
- debian/rules
- debian/shadowsocks-rust-local@.service
- debian/shadowsocks-rust-server@.service
- debian/shadowsocks-rust.service
> Refine debian packaging

- src/crypto/aead.rs
The old implementation dose nothing to the nonce, because `prev` is 0.
See also https://github.com/jedisct1/libsodium/blob/569778b517496861a3880e0e690973bf08a52e08/src/libsodium/sodium/utils.c#L239
> fix increase_nonce

- src/relay/tcprelay/server.rs
- src/relay/tcprelay/socks5_local.rs
These additions are similar to those in 271e24d, which were then
removed during the transition to futures and tokio in 5bf6560.
> Add `set_nodelay` and `set_keepalive`

- .travis.yml
It looks like, from the config, that you want the CI to run on all three release channel. However, it looks like Travis actually only runs on stable currently. This should hopefully fix that.
> Fix .travis.yml to actually build on beta and nightly

- Cargo.toml
- src/crypto/cipher.rs
- src/crypto/mod.rs
- src/crypto/openssl.rs
- src/crypto/stream.rs
Hi. Would it be OK to feature gate the RC4 cipher? This crypto is considered quite broken, and we are trying to link towards our a stripped down version of OpenSSL without RC4 support. We can't do that while this crate is using RC4 functions however.
I have enabled this feature by default, so merging this PR should not cause any real change to the project as is, but for those who want to get rid of RC4 they can now build with `--no-default-features` if they want to.
> Feature gate RC4 cipher

- src/crypto/cipher.rs
- src/relay/dns_resolver.rs
When compiling without the `sodium` feature I get a compile warning that a constant is unused. So I added conditional compilation to that constant.
Clippy also showed me that an assignment could be simplified.
> Fix unused warning, simplify assignment

- src/config.rs
- src/crypto/cipher.rs
- src/relay/socks5.rs
- src/relay/tcprelay/mod.rs
- src/relay/tcprelay/server.rs
- src/relay/tcprelay/socks5_local.rs
- src/relay/udprelay/server.rs
I hope this does not come off as me complaining about style, that is not my intention :)
I just opened the code in my IDE that runs the Clippy linter on everything by default, and I noticed a few things it mentioned. Passing `Copy` types around by reference is not needed, and discouraged by Clippy since it can lead to less optimal code being generated. This PR makes the `Copy` types be sent by value instead.
> Don't pass around Copy types as references

- src/bin/ssurl.rs
- src/config.rs
- src/context.rs
- src/crypto/aead.rs
- src/crypto/cipher.rs
- src/crypto/mod.rs
- src/crypto/ring.rs
- src/crypto/sodium.rs
- src/crypto/table.rs
- src/lib.rs
- src/monitor.rs
- src/plugin/mod.rs
- src/relay/dns.rs
- src/relay/loadbalancing/server/roundrobin.rs
- src/relay/socks5.rs
- src/relay/tcprelay/context.rs
- src/relay/tcprelay/crypto_io.rs
- src/relay/tcprelay/mod.rs
- src/relay/tcprelay/server.rs
- src/relay/tcprelay/socks5_local.rs
- src/relay/tcprelay/stream.rs
- src/relay/tcprelay/utils.rs
- src/relay/udprelay/dns.rs
- src/relay/udprelay/local.rs
- src/relay/udprelay/mod.rs
- src/relay/udprelay/server.rs
This started out with seeing that `Plugin.addr` seemed unused. So I removed it and wanted to send a PR. To get some feedback if it was indeed unused, or if I had missed something about it.
Then I also saw that rustfmt suggested some changes. So I applied that. And then I saw Clippy had a few things to suggest. So I went ahead and applied some of the suggestions it had.
This PR should not change any behavior or exposed API. Except the `Plugin::addr()` method which is now gone.
> Misc simplification

- .travis.yml
Would be nice to be able to run CI tests on Windows. To make sure it does not break.. Also there seems to be issues building the crate on Windows right now. So would be good to get that resolved as well. As such I have marked the Windows build as OK to fail for now.
In the process `cache: cargo` got lost. I have personally not really seen any speedup with caching. Cargo generates a huge amount of data. And the time it takes to download and unpack this on build start and then pack and upload again on a finished build is usually longer than it just takes to do a clean build.
Also, to not make the CI run forever I opted for not running all three Rust versions on all platforms. Keeping `beta` and `nightly` on Linux but only testing `stable` on the other two platforms. What do you think about …
> Test on windows

- src/bin/local.rs
- src/bin/logging/mod.rs
- src/bin/server.rs
- src/bin/ssdns.rs
There was a lot of logging setup code that was shared between the binaries. I reduced duplication a lot by sharing the code via a module. Easier to keep in sync, is one benefit.
> Move logging code into reused module

- src/relay/utils.rs
RLIMT_NOFILE is private in Android system, so just disable the function here.
Not sure if this change will break the build/function on other platforms.
> Disable set_nofile in Android build

- src/context.rs
If disabling the `trust-dns` feature, there will be a compilation error, as `dns_resolver` is not defined.
> Fix the build without trust-dns

- src/acl/mod.rs
- src/context.rs
- src/relay/dnsrelay/mod.rs
1. Fix the return value of `acl::check_ip_in_proxy_list`.
2. Fix the condition order in `context::check_ip_in_proxy_list`
3. Keep the value whether the qname is resolved by remote or local in `add_to_reverse_lookup_cache`
Tested locally, all routes in Android client should work now.
> Fix bugs in #235

- src/context.rs
> Refine reverse_lookup_cache

- Cargo.lock
- Cargo.toml
- src/acl/mod.rs
- src/context.rs
- src/relay/dnsrelay/mod.rs
- src/relay/dnsrelay/upstream.rs
I am not going to pretend I know what I am doing with these code.
> Refactoring for configurable DNS upstreams & some other refinements

- .circleci/config.yml
- Cross.toml
- build/Dockerfile.aarch64-unknown-linux-gnu
- build/build-release
Latest Ubuntu Server 20.04 LTS released with rpi 64bit support.
It might be better than using Raspbian.
https://ubuntu.com/download/raspberry-pi
> [#243] Support cross compiling for aarch64-unknown-linux-gnu

- src/acl/mod.rs
- src/relay/dnsrelay/mod.rs
As we examine CNAME records in answer section and possibly A/AAAA records in additional section, we should only skip the second stage only if the entire ACL is empty.
> Be more conservative when skipping resolving

- Cargo.toml
- src/relay/tcprelay/http_local.rs
- src/relay/tcprelay/proxy_stream.rs
pin-project will deprecate the project attribute due to some unfixable
limitations.
Refs: https://github.com/taiki-e/pin-project/issues/225
*Although the deprecation of the project attribute has not been released yet, this PR is submitted in advance to avoid the CI from being broken by deprecated warnings.*
> Remove uses of pin_project::project attribute

- src/relay/local.rs
- src/relay/tcprelay/proxy_stream.rs
This reverts commit 205eaa95addbb56fccc3d0d34705a92e79c8086b.
Reported in this bug: https://github.com/shadowsocks/shadowsocks-android/issues/2561
Also fix the tx/rx in ProxyStream
> Fix the tx/rx update in ProxyStream

- src/plugin/ss_plugin.rs
Remove the previous hack, according to the discussion here: https://github.com/shadowsocks/shadowsocks-rust/pull/278
> Remove the VPN option hack

- src/bin/local.rs
- src/bin/server.rs
- src/bin/ssurl.rs
Fixed #284 
> conflicts_with
> > NOTE: Conflicting rules take precedence over being required by default. Conflict rules only need to be set for one of the two arguments, they do not need to be set for each.
> Fix `conflicts_with` related errors

- .circleci/config.yml
- .github/workflows/build-release.yml
- Cross.toml
- build/Dockerfile.arm-unknown-linux-musleabi
- build/build-release
Some old routers (like xiaomi R1D/R2D) could use arm-unknown-linux-musleabi release.
> Add arm-unknown-linux-musleabi release

- src/bin/local.rs
- src/bin/server.rs
- src/config.rs
- src/plugin/mod.rs
- src/plugin/obfs_proxy.rs
- src/plugin/ss_plugin.rs
- src/relay/manager.rs
To be used by https://github.com/shadowsocks/shadowsocks-android/pull/2585.
@madeye Please review?
> Allow passing in an optional plugin_arg

- build/Dockerfile.arm-unknown-linux-musleabi
Use cross build docker image `rustembedded/cross:arm-unknown-linux-musleabi-0.2.1`. Waiting for this issue solved: https://github.com/rust-lang/libc/issues/1848 , then we can back to image `rustembedded/cross:arm-unknown-linux-musleabi`
> Fix arm-unknown-linux-musleabi build

- build/Dockerfile.mips-unknown-linux-musl
- build/Dockerfile.mipsel-unknown-linux-musl
Waiting this issue fixed: https://github.com/rust-lang/libc/issues/1848
Then we can switch back to `mips-unknown-linux-musl`
Fix #311
> Fix #311. Fix mips and mipsel build

- Cargo.toml
The `opt-level = "z"` reduces target binaries to 80-90%.
If we `strip` it up, it will reduces to ≈55%.
- "z" on origin:
|           |   origin   | "z" opt-ed | SHRINK |
|-----------|-----------:|-----------:|-------:|
| sslocal   | 12,956,312 | 11,106,768 | 85.72% |
| ssserver  | 11,103,240 |  9,830,544 | 88.54% |
| ssurl     |  4,808,248 |  4,221,328 | 87.79% |
| ssmanager | 11,216,072 |  9,924,528 | 88.48% |
- "z" on `strip`-ed origin:
|           | `strip`-ed origin | "z" opt-ed | SHRINK |
|-----------|------------------:|-----------:|-------:|
| sslocal   |         9,089,056 |  7,274,528 | 80.03% |
| ssserver  |         7,392,928 |  6,266,528 | 84.76% |
| ssurl     |         2,535,872 |  2,310,592 | 91.12% |
| ssmanager |         7,503,520 |  6,344,352 | 84.55% |
- "z" + `strip` on …
> minimize target file in size

- crates/shadowsocks-service/src/local/loadbalancing/ping_balancer.rs
- crates/shadowsocks-service/src/local/loadbalancing/server_stat.rs
- Treat timeouts as failures, so requests that receive no response count as failures.
- Increase check timeout from 2s to 5s to avoid penalties on slow servers.
- Increase check interval from 6s to 10s.
> 🏓 Ping balancer: treat ping timeouts as failures

- README.md
- crates/shadowsocks-service/src/config.rs
See shadowsocks/shadowsocks-rust#394
This is a lazy implementation that simply filters for `disable` before the vector of `shadowsocks::ServerConfig` is created.
- Benefit: simply, lazy, no memory usage, no modification to `shadowsocks::ServerConfig`
- Downside: `Display` trait for `shadowsocks_service::Config` is not aware of disabled servers
> Lazy server disable implementation

- .github/workflows/build-release.yml
This adds i386 builds in workflow.
BTW, I'm confused with the difference between `arm-unknown-linux-musleabihf` and
`armv7-unknown-linux-musleabihf`, would anyone tell me that? Thanks so much.
> add release i386

- Cargo.lock
- bin/sslocal.rs
- bin/ssmanager.rs
- bin/ssserver.rs
- crates/shadowsocks-service/Cargo.toml
- crates/shadowsocks-service/src/local/context.rs
- crates/shadowsocks-service/src/local/http/client_cache.rs
- crates/shadowsocks-service/src/local/net/tcp/auto_proxy_stream.rs
- crates/shadowsocks-service/src/local/net/udp/association.rs
- crates/shadowsocks-service/src/local/redir/udprelay/mod.rs
- crates/shadowsocks-service/src/local/tunnel/udprelay.rs
- crates/shadowsocks-service/src/server/udprelay.rs
- crates/shadowsocks/Cargo.toml
- tests/tunnel.rs
- UDP associations that are not often used, like DNS queries, should be evicted firstly.
- UDP redir caches respond sockets that binds to non-local addresses to prevent creating sockets repeatedly.
> Manage UDP associations with LFU strategy

- crates/shadowsocks/src/relay/tcprelay/aead.rs
- crates/shadowsocks/src/relay/tcprelay/stream.rs
- crates/shadowsocks/src/relay/udprelay/crypto_io.rs
This removes a carefully engineered feature (proposed in https://github.com/shadowsocks/shadowsocks-org/issues/44#issuecomment-280007952) to detect Shadowsocks as per https://github.com/net4people/bbs/issues/22. Testing in progress.
> Remove the behavior of silent dropping replay packets

- crates/shadowsocks-service/src/local/dns/client_cache.rs
Our UNIX stream based DNS lookup doesn't support connection reuse.
> Remove the reuse for UNIX stream DNS lookup.

- .github/workflows/build-docker-image.yml
- Dockerfile
- examples/config.json
Resolved #570. Provide multi-arch Docker support for shaodowsocks-rust.
> Add Docker and its GitHub Actions auto build support

- snap/snapcraft.yaml
Resolved #617. It can now use config file under `$HOME` path via `-c` or `--config` parameter.
> Add support for snap application using config file

- README.md
- crates/shadowsocks-service/src/acl/mod.rs
- crates/shadowsocks-service/src/acl/sub_domains_tree.rs
I have about 320000 hostnames rules and with regexps both performance and memory consumption are abysmal. Hashsets are much faster and smaller in my case. Memory decreased from 2.8GB to 35MB. It's possible to increase performance even further - replace default hasher with [ahash](https://github.com/tkaitchuck/aHash), but since it requires to add new package I'll leave that decision for you.
I added hashsets' parsing in backward-compatible fashion, so old rules will work without any changes. Also I added an optimization to regexp matcher. Since all dns records are encoded in ASCII, there is no need for unicode support in regexes.
> Add hashset-mode into ACL rules

- README.md
- crates/shadowsocks-service/src/acl/mod.rs
Fixes error `error: pattern can match invalid UTF-8` in regular expressions. It still rejects unicode characters with another error `error: Unicode not allowed here` but that's fine since there is no unicode characters in dns records anyway.
> Use byte regexes to fix compiltation error

- .github/workflows/build-and-test.yml
- .github/workflows/build-release.yml
Currently we can only use x86_64 macOS to cross-build aarch64 platform, which is this PR try to do.
For #569
> CI: build check and release for Apple Silicon

- Dockerfile.v2ray
If this is to go into the Docker image release workflow, it needs to pull the correct architecture version of the plugin.
> Add v2ray-plugin Docker image example

- crates/shadowsocks-service/src/local/redir/server.rs
- crates/shadowsocks-service/src/local/socks/server/mod.rs
- crates/shadowsocks-service/src/local/tunnel/server.rs
The space in `simultaneously in` was removed by mistake.
> fix spelling

- Cargo.lock
- README.md
- crates/shadowsocks-service/Cargo.toml
- crates/shadowsocks-service/src/config.rs
- crates/shadowsocks-service/src/local/mod.rs
- crates/shadowsocks-service/src/local/redir/redir_ext.rs
- crates/shadowsocks-service/src/local/redir/sys/mod.rs
- crates/shadowsocks-service/src/local/redir/tcprelay/mod.rs
- crates/shadowsocks-service/src/local/redir/tcprelay/sys/unix/bsd.rs
- crates/shadowsocks-service/src/local/redir/tcprelay/sys/unix/linux.rs
- crates/shadowsocks-service/src/local/redir/udprelay/sys/unix/bsd.rs
- crates/shadowsocks-service/src/local/redir/udprelay/sys/unix/linux.rs
- crates/shadowsocks-service/src/local/socks/server/socks5/udprelay.rs
- crates/shadowsocks-service/src/local/tunnel/udprelay.rs
- crates/shadowsocks-service/src/manager/mod.rs
- crates/shadowsocks-service/src/server/mod.rs
- crates/shadowsocks-service/src/server/server.rs
- crates/shadowsocks-service/src/server/udprelay.rs
- crates/shadowsocks/src/net/mod.rs
- crates/shadowsocks/src/net/option.rs
- crates/shadowsocks/src/net/sys/mod.rs
- crates/shadowsocks/src/net/sys/unix/mod.rs
- crates/shadowsocks/src/net/sys/windows/mod.rs
- crates/shadowsocks/src/net/tcp.rs
- crates/shadowsocks/src/net/udp.rs
- crates/shadowsocks/src/relay/udprelay/proxy_socket.rs
This is useful for creating multiple local / server instances listening on both `::` and `0.0.0.0` with the same port.
Listener sockets (both TCP and UDP) in redir local is now `IPV6_V6ONLY=1` because transparent proxies couldn't handle V4 and V6 packets simultaneously properly.
`ipv6_only` is currently only in the top level of the configuration. So `ipv6_only: true` will be applied to all local and server instances. It is Ok in common use cases.
> Support ipv6_only socket option (IPV6_V6ONLY)

- src/service/local.rs
Small drive by change to update the output of sslocal -h to point at the updated wiki URL
> Update sslocal server-url help string

- debian/changelog
- debian/shadowsocks-rust-local@.service
- debian/shadowsocks-rust-server@.service
- debian/shadowsocks-rust.default
- debian/shadowsocks-rust.init
- debian/shadowsocks-rust.postinst
- debian/shadowsocks-rust.service
There are some problems with the current script.
1. Unable to bind ports (port < 1024)
bind the low port will prompt ```Permission denied```
solution: add AmbientCapabilities config.
2. changlog has some problem
For example, compile with a warning.
```
dpkg-source: warning: shadowsocks-rust/debian/changelog(l20): found start of entry where expected more change data or trailer
```
3. replace sserver/sslocal to ssservice.
4. removed some wrong startup parameters.
The following commands will work properly after updating the script.
```
sudo systemctl start shadowsocks-rust.service
```
> Update debian deb script

- README.md
- k8s/chart/.helmignore
- k8s/chart/Chart.yaml
- k8s/chart/templates/NOTES.txt
- k8s/chart/templates/_helpers.tpl
- k8s/chart/templates/config.yaml
- k8s/chart/templates/deployment.yaml
- k8s/chart/templates/hpa.yaml
- k8s/chart/templates/service.yaml
- k8s/chart/templates/serviceaccount.yaml
- k8s/chart/templates/tests/test-connection.yaml
- k8s/chart/values.yaml
- k8s/shadowsocks-rust.yaml
- helm chart
- kubectl with raw manifest which generated via helm
- update README
One more thing, we could host the chart repo with GitHub pages or within a Docker oci image.
> feat(deploy): support k8s deployment (#739)

- Cargo.toml
Adds strip option since it was [stabilized](https://github.com/rust-lang/cargo/pull/10088). Closes #276.
> Strip symbols in release mode

- Cargo.toml
By default mimalloc has ["secure"](https://github.com/microsoft/mimalloc#secure-mode) feature enabled which has some performance penalty and a little memory overhead (due to guard pages). It's useless for safe rust code, but can be useful for unsafe. I'm not sure if it useful for shadowsocks-rust project, but personally I disable it in my builds.
> Disable secure mode in mimalloc allocator

- crates/shadowsocks/src/context.rs
I wrote little rust. So it is welcome to tell me any problems in the commit.
The feature `security-iv-printable-prefix` works well for me. I found the original solution used `Rand` package to generate the index. It is repeated for nonce calculation. So I updated the codes to prefix processing of nonce.
> update: remove rnd from security-iv-printable-prefix feature

- Cargo.lock
- Cargo.toml
- bin/sslocal.rs
- bin/ssmanager.rs
- bin/ssserver.rs
- bin/ssservice.rs
- src/lib.rs
- src/service/local.rs
- src/service/manager.rs
- src/service/server.rs
Since Rust 1.61.0, the `main` function can return a type that implements the `Termination` trait. By this, the `main` function can return custom exit codes, so use this.
This replaces `std::process::exit()`. Also, using `std::process::ExitCode` for the return type, considering the possibility of using the own exit code.
Also, I am replacing [`exitcode`](https://crates.io/crates/exitcode) with [`sysexits`](https://crates.io/crates/sysexits) for return the system exit code constants as defined by `<sysexits.h>` from the `main` function.
ref: [Announcing Rust 1.61.0](https://blog.rust-lang.org/2022/05/19/Rust-1.61.0.html)
> Change the return type of the `main` function

- src/lib.rs
- src/service/local.rs
- src/service/manager.rs
- src/service/server.rs
I noticed `sslocal` was exiting with `0` when run completely naked (no args), which surely isn't correct. This fixes that.
I don't think it would cause problems downstream, although I cannot be absolutely sure.
> `sslocal`, `ssservice`, `ssmanager` return non-zero exit codes when failing to launch

- crates/shadowsocks-service/src/local/socks/server/socks5/udprelay.rs
- crates/shadowsocks-service/src/server/udprelay.rs
测试环境： 两台笔记本，连接在同一个wifi下
`iperf3 -s` 以及 `ss-server` 运行在一台电脑
`iperf3 -s` 以及 `ss-local` 运行在一台电脑上
测试命令: `iperf3 -c 127.0.0.1 -p 9700 -b 100M -u -l 1260` 
随着 -b 参数的改变，传输速率极速下降
| -b | c->s bps | c->s size | c->s lost | s->c bps | s->c size | s->c lost |
|-------|----------|-----------|-----------|----------|-----------|-----------|
| 100M  | 100M     | 119M      | 0%        | 8M       | 9M        | 1%        |
| 200M  | 107M     | 128M      | 0%        | 8M       | 9M        | 1%        |
| 400M  | 111M     | 132M      | 0%        | 8M       | 9M        | 1%        |
| 800M  | 113M     | 134M      | 0%        | 8M       | 9M        | 1%        |
| -b | c->s bps | c->s size | c->s lost | s->c bps | s->c size | s->c lost |
|-------|----------|-----------|-----------|----------|-----------|-------- …
> UDP relay 传输性能随着发送速率增加极速下降

- Dockerfile
- docker/docker-entrypoint.sh
- Remove useless configuration.
- Docker container running as root user, the program running as nobody user
For specific reasons, please refer to [shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev/pull/2912).
Final result:
```bash
$ docker container logs condescending_dubinsky
/usr/local/bin/docker-entrypoint.sh: Configuration complete; ready for start up
INFO  shadowsocks server 1.15.0-alpha.5 build 2022-06-29T07:26:50.397766052+00:00
INFO  shadowsocks tcp server listening on 127.0.0.1:8388, inbound address 127.0.0.1:8388
```
> Minor update

- crates/shadowsocks-service/src/local/socks/server/socks5/udprelay.rs
- crates/shadowsocks-service/src/server/udprelay.rs
Reverts shadowsocks/shadowsocks-rust#877
> Revert "UDP relay 传输性能随着发送速率增加极速下降"

- crates/shadowsocks-service/src/local/dns/dns_resolver.rs
I was testing ss-rust, and somehow it prints 2 error with the exact same message, turns out it's a typo, so I made a fix.
> Fix typo in file 'dns_resolver.rs'.

- k8s/chart/templates/service.yaml
- k8s/chart/values.yaml
Useful feature for k8s-guys (for example, external-dns needs service annotations)
> Helm: add service annotations

- Cargo.lock
- Cargo.toml
- crates/shadowsocks-service/Cargo.toml
- crates/shadowsocks/Cargo.toml
- crates/shadowsocks/src/context.rs
For https://github.com/shadowsocks/shadowsocks-org/issues/204.
> 🚮 Remove `security-iv-printable-prefix` feature

- crates/shadowsocks/src/config.rs
Some URLs contain a base64 string with `=` char (e.g: `ss://YWVzLTEyOC1nY206c2hhZG93c29ja3M=@1.2.3.4:8000#tag`) which breaks the `ssurl` tool.
> fix(ssurl): use `percent_decode_str` for `userinfo` encoded data

- crates/shadowsocks/src/relay/socks5.rs
- crates/shadowsocks/src/relay/udprelay/aead.rs
- crates/shadowsocks/src/relay/udprelay/aead_2022.rs
- crates/shadowsocks/src/relay/udprelay/crypto_io.rs
- crates/shadowsocks/src/relay/udprelay/proxy_socket.rs
- crates/shadowsocks/src/relay/udprelay/stream.rs
so that it allows the socket to be wrapped into Stream/Sink easily
> Implemented poll_* family functions on UDP ProxySocket

- crates/shadowsocks/src/relay/tcprelay/aead.rs
in version 1.14.3
```
// Check repeated salt after first successful decryption #442
if self.salt.is_some() {
let salt = self.salt.take().unwrap();
context.check_nonce_replay(&salt)?;
}
```
current master version
```
// Check repeated salt after first successful decryption #442
if let Some(ref salt) = self.salt {
context.check_nonce_replay(self.method, salt)?;
}
```
if enable feature `security-replay-attack-detect`, it causes error `detected repeated nonce (iv/salt)`
> bugfix: salt recheck will cause duplicated iv/salt error

- crates/shadowsocks-service/src/config.rs
- crates/shadowsocks-service/src/manager/server.rs
- crates/shadowsocks/src/config.rs
- src/service/genkey.rs
This PR tries to deal with API change when bumping base64 to 0.21.
- base64 v0.21.0 docs: https://docs.rs/base64/0.21.0/base64/index.html
- base64 v0.13.1 docs: https://docs.rs/base64/0.13.1/base64/index.html
> Deal with API change when bumping base64 to 0.21

- crates/shadowsocks-service/src/config.rs
- crates/shadowsocks-service/src/local/mod.rs
- crates/shadowsocks-service/src/local/tun/mod.rs
- src/service/local.rs
- src/vparser/mod.rs
This PR adds a new argument `--tun-interface-destination` to the `tun` mode. Also, it enables the address format with full 32 bit mask like `10.250.0.1/32`, though seems the package `tun` has a bit problem supporting that for macos.
```
utun10: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
inet 10.175.0.8 --> 10.175.0.7 netmask 0xff000000
```
> Enable tun destination configuration

- crates/shadowsocks-service/src/config.rs
Reverts shadowsocks/shadowsocks-rust#1106
There are some fields only for binaries: https://github.com/shadowsocks/shadowsocks-rust/blob/a9601f30f9f083e59dd4f2a964092cfa601eab75/src/config.rs#L260-L265 .
> Revert "⛔ config: deny unknown fields"

- Cargo.lock
- crates/shadowsocks-service/Cargo.toml
related https://github.com/meh/rust-tun/pull/56
Not meant to merge this patch directly, just want to raise the netmask problem from dependency `rust-tun`. Seems that package is not actively maintained.
> macOS fix netmask API

- .github/workflows/build-and-test.yml
- .github/workflows/build-docker-image.yml
- .github/workflows/build-nightly-release.yml
- .github/workflows/build-release.yml
- .github/workflows/clippy-check.yml
Currently the workflow is using `actions/checkout@v2`, which is outdated and generates warnings in workflow logs. This PR upgrade `actions/checkout` to the latest `v3`.
There are also two actions `actions-rs/toolchain` and `actions-rs/clippy-check` from [actions-rs](https://github.com/actions-rs/) in use, which is also outdated and haven't been updated in years.
This PR replaces `actions-rs/toolchain` with bare `rustup` commands, since `rustup` is included in GitHub Actions runner images (see [actions/runner-images](https://github.com/actions/runner-images)).
However there seems to be no easy way for replacing `actions-rs/clippy-check`. So, I'm marking this a draft PR and open for further discussions.
> Deal with warnings caused by outdated actions in workflows

- crates/shadowsocks-service/src/config.rs
- crates/shadowsocks-service/src/local/mod.rs
- crates/shadowsocks-service/src/manager/mod.rs
- crates/shadowsocks-service/src/server/mod.rs
- crates/shadowsocks/src/net/option.rs
- crates/shadowsocks/src/net/sys/unix/bsd/freebsd.rs
- crates/shadowsocks/src/net/sys/unix/bsd/macos.rs
- crates/shadowsocks/src/net/sys/unix/linux/mod.rs
- crates/shadowsocks/src/net/sys/unix/mod.rs
- crates/shadowsocks/src/net/sys/unix/others.rs
- crates/shadowsocks/src/net/sys/windows/mod.rs
- crates/shadowsocks/src/net/tcp.rs
- src/service/local.rs
- src/service/manager.rs
- src/service/server.rs
- Currently support macOS (Client Only) and Linux (> 5.19)
- ref #1156
> feat(mptcp): Basic implementation of Multipath-TCP

- crates/shadowsocks/src/relay/udprelay/mod.rs
Since the `ProxySocket` interface is not versatlie enough (i.e. require a ShadowUdpSocket under it), developers may need write their own structs based on cryptography tools the crate offers. However, the corresponding module `udprelay/crypto_io` is private, making this difficult. 
This pull request makes `udprelay/crypto_io` module public to solve this problem. It's also the counterpart of `tcprelay/crypto_io`, which has been public in the latest release.
> Make udprelay/crypto_io public

- Cargo.lock
- Cargo.toml
- crates/shadowsocks-service/Cargo.toml
- crates/shadowsocks-service/src/config.rs
- crates/shadowsocks-service/src/dns/mod.rs
- crates/shadowsocks-service/src/local/dns/dns_resolver.rs
- crates/shadowsocks-service/src/local/dns/server.rs
- crates/shadowsocks/Cargo.toml
- crates/shadowsocks/src/dns_resolver/resolver.rs
- crates/shadowsocks/src/dns_resolver/trust_dns_resolver.rs
- crates/shadowsocks/src/net/sys/unix/bsd/freebsd.rs
- crates/shadowsocks/src/net/sys/unix/bsd/macos.rs
- crates/shadowsocks/src/net/sys/unix/linux/mod.rs
- crates/shadowsocks/src/net/sys/unix/others.rs
- crates/shadowsocks/src/net/sys/windows/mod.rs
- crates/shadowsocks/src/net/udp.rs
- src/service/local.rs
- DNS socket applies outbound configurations. Depending on: https://github.com/bluejekyll/trust-dns/issues/1335
Outbound configurations, like outbound-fwmark, outbound-bind-interface, outbound-bind-addr, ... will also applies to the TCP/UDP sockets created by trust-dns DNS resolver.
NOTE: On Android platform, DNS sockets will also be protected.
- socket2 v0.5, https://github.com/rust-lang/socket2/issues/405
- MPTCP: https://github.com/shadowsocks/shadowsocks-rust/issues/1156
> Next Release: v1.16

- crates/shadowsocks/src/net/udp.rs
I've just added support for building and running ShadowSocks on iOS. We've used it as a library, and it works well enough for our usecase. Would be great to see this upstreamed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shadowsocks/shadowsocks-rust/1194)
> Allow creating UDP sockets on iOS

- src/config.rs
- src/service/local.rs
- src/service/manager.rs
- src/service/server.rs
Currently if you run `snap start shadowsocks-rust.ssserver-daemon` it will fail because of the missing config.
This patch adds paths to config files. All a user needs to do is to add desired local/server configs to $SNAP_COMMON directory.
Still there's a problem, that only one `sslocal`/`ssserver` daemon instance is allowed.
With `ssserver` you can work around this by runing multiple servers in one process (shadowsocks config allows it).
But with `sslocal` this is, alas, impossible.
> Added configs for snap daemons

- README.md
- crates/shadowsocks-service/src/config.rs
- crates/shadowsocks-service/src/dns/mod.rs
- crates/shadowsocks-service/src/local/mod.rs
- crates/shadowsocks-service/src/manager/mod.rs
- crates/shadowsocks-service/src/server/mod.rs
- crates/shadowsocks/src/dns_resolver/resolver.rs
- crates/shadowsocks/src/dns_resolver/trust_dns_resolver.rs
- src/service/local.rs
- src/service/manager.rs
- src/service/server.rs
See also #1215
This PR adds a command-line option `--dns-cache-size` to `sslocal`, `ssserver` and `ssmanager`, allowing users to configure the `cache_size` of `ResolverOpts` in trust-dns.
I'm not sure if the current solution is appropriate, i.e. to pass `dns_cache_size` all the way to `create_resolver`. How about I pass the `dns_cache_size` through a `ResolverOpts`?
> Add command-line option "dns-cache-size" for trust-dns

- README.md
Mention IPv6 problem with docker and link to IPv6 documentation for docker.
> Add IPv6 warning for docker

- crates/shadowsocks-service/src/acl/mod.rs
the generated acl file by running `genacl_proxy_gfw_bypass_china_ip.py` does not correctly match the pattern in `src/acl/mod.rs`.
the old version will use heavy regex set rules and it will compile all patterns when the first time used. Instead of using tree subdomain methods. 
Actually, most rules are generated for subdomain tree. By removing the last duplicated `\$`, we can make it right.
If it is not right or has some problem, please comment here.
> bugfix: acl rule pattern match error for tree rule

- README.md
- crates/shadowsocks-service/src/config.rs
> [Regression fix] local DNS uses mode `tcp_and_udp` by default

- Cargo.lock
- Cargo.toml
- bin/ssurl.rs
ssurl now supports parsing ssconf links
This is [outline's](https://github.com/Jigsaw-Code/outline-client) way of [providing dynamic key configuration](https://www.reddit.com/r/outlinevpn/wiki/index/dynamic_access_keys/) which is similar to [SIP008](https://github.com/shadowsocks/shadowsocks-rust/issues/302).
The `ssconf://` link is the same as `https://` link to `ss://` configuration (`json` in this implementation is not supported though it is easy to implement in the future)
Outline is based on shadowsocks protocol but has no official cli interface (for clients). My provider is using dynamic keys and since [shadowsocks-rust#302](https://github.com/shadowsocks/shadowsocks-rust/issues/302) (SIP008) is WIP this "hack" will allow using shadowsocks-rust with dynamic keys at least for now …
> ssurl: add support for SIP008 links (ssconf links with ss contents)

- crates/shadowsocks-service/src/config.rs
- crates/shadowsocks-service/src/local/dns/client_cache.rs
- crates/shadowsocks-service/src/local/dns/server.rs
- crates/shadowsocks-service/src/local/mod.rs
for each client key type (tcplocal, tcpremote, udplocal, udpremote), the cache client size is set 5. we can not configure the dns cache size dynamically. If the size is too small, the dns client will create new connections and discard the old ones which are still waiting for dns responses. And it leads to timeout and slow down the dns service.
So in the PR, it add a new configurable parameter for dns local `client_cache_size`, the default value is 5. 
In my own openwrt device, it works much better.
> feature: add support to config dns client cache size

- README.md
- crates/shadowsocks-service/src/config.rs
the config item client_cache_size is missed in SSLocalExtConfig, which is to parse the config.json file.
This PR fixed it and updated README file
> bugfix: fix missed client_cache_size config item in SSLocalExtConfig

- debian/changelog
debian build reports error:
```
dpkg-gencontrol: error: source package has two conflicting values - shadowsocks-rust and shadosocks-rustdh_gencontrol: error: dpkg-gencontrol -pshadowsocks-rust -ldebian/changelog -Tdebian/shadowsocks-rust.substvars -Pdebian/shadowsocks-rust returned exit code 255
```
we should use `dch -i` which is from devscripts to update changelog.
> debian: fixup changelog format

- crates/shadowsocks/Cargo.toml
so that it doesn't rely on older version of ring-compat which adds ring 0.16 to graphs
> update shadowsocks-crypto to latest

- crates/shadowsocks/src/net/tcp.rs
Incoming buffer sizes are read by config but not actually set on the socket.
tokio TcpSocket gained the ability finally to set this.
This PR sets the incoming socket buffer snd/rcv buffer on the TcpSocket in a cross platform manner.
> Set the incoming socket buffer sizes properly on the listen socket.

- crates/shadowsocks-service/src/local/tun/tcp.rs
> fix: synchronize SYN packet and Socket creation

- crates/shadowsocks-service/src/config.rs
- crates/shadowsocks-service/src/manager/server.rs
- crates/shadowsocks-service/src/server/mod.rs
The PR helps set `outbound_fwmark` in TCP connection options for different server configs.
With this feature, we do not need to start multiple server processes, to support different outbound tunnels. Now many websites forbid access from some VPS IPs. We may need to switch our proxy servers with special browser plugins, for example `OmegaSwitchy`.  
Another solution is to setup split-tunnels after the server, which is already supported by `V2Ray`. The server will choose the right tunnel based on the domain address. 
I think the `fwmark` is the best solution for distinguishing TCP data packages. In my case, I setup `wireguard` and route rules with `fwmark`, to route marked data packages to different servers. It works well. 
Why not `outbound_interface`? I ever had some problem for ipv6 …
> feature: support fwmark in server side to split outbound tunnel

- crates/shadowsocks/Cargo.toml
TFO is only enabled for Windows, Linux, Android, macOS (iOS, ...), FreeBSD. fix #1487
> fix(shadowsocks): tokio-tfo deps only for supported platforms

- crates/shadowsocks-service/src/config.rs
> add launchd_udp_socket_name / launchd_tcp_socket_name to basic config

- crates/shadowsocks-service/src/local/loadbalancing/ping_balancer.rs
- crates/shadowsocks-service/src/local/loadbalancing/server_data.rs
- crates/shadowsocks-service/src/local/mod.rs
- src/service/local.rs
This is the first part of #1491.
Symptom: Assume the following config:
```
{
"servers": [
{
"server": "192.0.2.1",
"server_port": 8388,
...
"outbound_fwmark": 1
},
{
"server": "192.0.2.1",
"server_port": 8388,
...
"outbound_fwmark": 2
}
]
}
```
The load balancer will ignore the fwmark field. We will see all outbound traffic does not set any fwmark.
Proposed fix:
1. PingBalancer now holds a ServerInstanceConfig which contains the correct information for outbound traffic.
2. The correct ConnectOpts is now built in the constructor of ServerIdent.
3. Now PingBalancer will get ConnectOpts from ServerIdent, instead of from context.
> Fix per-server outbound options not taking effect (part 1)

- crates/shadowsocks-service/src/config.rs
- crates/shadowsocks-service/src/local/http/utils.rs
- crates/shadowsocks-service/src/local/loadbalancing/server_data.rs
- crates/shadowsocks-service/src/local/net/tcp/auto_proxy_stream.rs
- crates/shadowsocks-service/src/local/net/udp/association.rs
- crates/shadowsocks-service/src/local/redir/tcprelay/mod.rs
- crates/shadowsocks-service/src/local/socks/server/socks4/tcprelay.rs
- crates/shadowsocks-service/src/local/socks/server/socks5/tcprelay.rs
- crates/shadowsocks-service/src/local/tun/tcp.rs
- crates/shadowsocks-service/src/local/tunnel/tcprelay.rs
- crates/shadowsocks-service/src/manager/server.rs
- crates/shadowsocks-service/src/server/mod.rs
I'm in a multi-WAN environment and I want the two WAN connections to backup each other. I tried to set outbound_fwmark for each server but it seems not working as expected.
By looking into the code I found two issues:
1. PingBalancer does not set the fwmark correctly in connect_opts so it's not able to detect whether the second WAN is working or not.
2. The outbound traffic seems to ignore the fwmark options in some cases. The connect_opts are modified correctly in some classes while not in others.
I drafted this change containing the following fixes:
1. Add outbound_bind_addr and outbound_bind_interface into ServerInstanceConfig
2. Refactor PingBalancer to hold a copy of per-server ConnectOpts
3. Add new interfaces for specifying ConnectOpts in AutoProxyClientStream
It works for my case, …
> Fix per-server outbound options not taking effect (part 2)

- crates/shadowsocks-service/src/local/tun/tcp.rs
It seems that 8ba1e326f6edf4c87a0e500aa3d3936bbd0e4c32 made connection opening non concurrent (since we await it from local-tun main loop). It seems to be huge performance loss (at least in my case it completely ruins usability)
> Make tcp socket creation non blocking

- Cargo.lock
fix https://github.com/shadowsocks/shadowsocks-rust/issues/1510
Rustls is a modern TLS library written in Rust.
`rustls::ConnectionCommon::complete_io` could fall into an infinite loop based on network input. When using a blocking rustls server, if a client send a `close_notify` message immediately after `client_hello`, the server's `complete_io` will get in an infinite loop. This vulnerability is fixed in 0.23.5, 0.22.4, and 0.21.11.
> fix: fix CVE-2024-32650

- crates/shadowsocks-service/src/local/redir/sys/unix/bsd_pf.rs
- crates/shadowsocks-service/src/local/redir/sys/unix/pfvar_bindgen_freebsd.rs
- crates/shadowsocks-service/src/local/redir/udprelay/sys/unix/bsd.rs
This pull request will fix this building errors on FreeBSD 14:
```
$> cargo build --features local-redir,local-socks4
Compiling shadowsocks-service v1.18.5 (shadowsocks-rust/crates/shadowsocks-service)
error[E0432]: unresolved import `super::pfvar::pfsync_state`
--> crates/shadowsocks-service/src/local/redir/sys/unix/bsd_pf.rs:22:5
|
22 |     pfsync_state,
|     ^^^^^^^^^^^^
|     |
|     no `pfsync_state` in `local::redir::sys::unix::pfvar`
|     help: a similar name exists in the module: `pfioc_state`
error[E0405]: cannot find trait `UdpSocketRedir` in this scope
--> crates/shadowsocks-service/src/local/redir/udprelay/sys/unix/bsd.rs:147:6
|
147 | impl UdpSocketRedir for UdpRedirSocket {
|      ^^^^^^^^^^^^^^
|
::: crates/shadowsocks-service/src/local/redir/redir_ext.rs:49:1
|
49  | pub …
```
> Fix: FreeBSD Building

- snap/snapcraft.yaml
This way we can call the applications without having to use the snap name before it's name. Eg: now: `shadowsocks-rust.sslocal` after applying `sslocal`
> [snap] Add aliases for all the non-daemon apps

- crates/shadowsocks/src/net/sys/mod.rs
```
warning: unused return value of `into_raw_fd` that must be used
--> crates/shadowsocks/src/net/sys/mod.rs:71:5
|
71 |     sock.into_raw_fd();
|     ^^^^^^^^^^^^^^^^^^
|
= note: losing the raw file descriptor may leak resources
= note: `#[warn(unused_must_use)]` on by default
```
> fix(net) losing the raw file descriptor may leak resources

- crates/shadowsocks/src/relay/udprelay/proxy_socket.rs
I need this in order to pass the file descriptor to [`VpnService.protect`](https://developer.android.com/reference/android/net/VpnService#protect(int)).
> Add `ProxySocket::as_raw_fd`

- crates/shadowsocks/src/context.rs
- crates/shadowsocks/src/dns_resolver/resolver.rs
- crates/shadowsocks/src/manager/datagram.rs
- crates/shadowsocks/src/manager/listener.rs
- crates/shadowsocks/src/net/tcp.rs
- crates/shadowsocks/src/net/udp.rs
- crates/shadowsocks/src/plugin/mod.rs
- crates/shadowsocks/src/relay/tcprelay/aead.rs
- crates/shadowsocks/src/relay/tcprelay/crypto_io.rs
- crates/shadowsocks/src/relay/tcprelay/proxy_listener.rs
- crates/shadowsocks/src/relay/tcprelay/proxy_stream/client.rs
- crates/shadowsocks/src/relay/tcprelay/proxy_stream/protocol/mod.rs
- crates/shadowsocks/src/relay/tcprelay/proxy_stream/protocol/v1.rs
- crates/shadowsocks/src/relay/tcprelay/proxy_stream/protocol/v2.rs
- crates/shadowsocks/src/relay/tcprelay/proxy_stream/server.rs
- crates/shadowsocks/src/relay/udprelay/proxy_socket.rs
- crates/shadowsocks/src/security/replay/mod.rs
- crates/shadowsocks/src/security/replay/ppbloom.rs
Most implementations are derived.
I would like to add `missing_debug_implementations` lint,
but before deriving more Debug implementations
we need to add Debug implementations to types exported
from `shadowsocks-crypto`.
Closes #1647
> feat(shadowsocks): add more Debug implementations

- crates/shadowsocks-service/src/net/mon_socket.rs
- crates/shadowsocks/src/net/udp.rs
- crates/shadowsocks/src/relay/udprelay/compat.rs
- crates/shadowsocks/src/relay/udprelay/mod.rs
- crates/shadowsocks/src/relay/udprelay/proxy_socket.rs
> take arbitrary IO for udp proxy

- crates/shadowsocks-service/src/local/redir/udprelay/sys/unix/freebsd.rs
- crates/shadowsocks-service/src/local/redir/udprelay/sys/unix/macos.rs
- crates/shadowsocks-service/src/local/redir/udprelay/sys/unix/openbsd.rs
- crates/shadowsocks/src/relay/udprelay/compat.rs
Fix a clippy warning that still shows up in https://github.com/shadowsocks/shadowsocks-rust/pull/1701/files.
And apply what clippy suggests for clippy::needless_lifetimes.
> chore: clippy fix

- crates/shadowsocks-service/src/local/redir/sys/mod.rs
Suppress the `unused_must_use` clippy warning that showed up in https://github.com/shadowsocks/shadowsocks-rust/pull/1718/files.
> chore: suppress a clippy warning

- crates/shadowsocks-service/src/local/http/http_client.rs
Fix a `clippy::useless_conversion` warning that showed up in https://github.com/shadowsocks/shadowsocks-rust/pull/1732/files.
> chore: fix clippy warning

- README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [shadowsocks Guru](https://gurubase.io/g/shadowsocks) to Gurubase. shadowsocks Guru uses the data from this repo and data from the [docs](https://shadowsocks.org/) to answer questions by leveraging the LLM.
In this PR, I showcased the "shadowsocks Guru", which highlights that shadowsocks now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution. …
> Introducing shadowsocks Guru on Gurubase.io

- crates/shadowsocks/src/config.rs
Closes https://github.com/shadowsocks/shadowsocks-rust/issues/1760
> fix: do not crash in ServerConfig::from_url() on unknown method

- crates/shadowsocks-service/src/local/tun/tcp.rs
I do not really know if we also need to flush other direction as well... Also not really sure that we should keep it opened after TcpSocketState::Close state - for example when we drop() it this will add unknown delay for writing buffers or failing
> fix: flush local-tun tcp writer half before close

- crates/shadowsocks-service/src/local/socks/server/server.rs
The same set of tests as in #1764
`config.json`
```json
{
"locals": [
{
"protocol": "socks",
"local_address": "127.0.0.1",
"local_port": 9090,
"socks5_auth_config_path": "auth.json"
}
],
"servers": [
{...}
],
}
```
`auth.json`:
```json
{
"password": {
"users": [
{
"user_name": "user",
"password": "password"
}
]
}
}
```
Tests:
```sh
$ curl -si --proxy socks5://127.0.0.1:9090 -U user:password https://api.seeip.org | head -4
HTTP/1.1 200 OK
Server: nginx/1.18.0 (Ubuntu)
Date: Mon, 11 Nov 2024 17:38:29 GMT
Content-Type: text/plain
```
```sh
$ curl -i --proxy socks5://127.0.0.1:9090 -U user:pass https://api.seeip.org 
curl: (97) User was rejected by the SOCKS5 server (1 255).
```
```sh
$ curl -i --proxy http://127.0.0.1:9090 -U us:pass https://api.seeip.org 
curl: (56) Recv failure: Connection …
```
> fix(sslocal): disallow HTTP/SOCKS4 proxying when authentication required

- README.md
- crates/shadowsocks-service/src/config.rs
- crates/shadowsocks-service/src/manager/server.rs
- crates/shadowsocks-service/src/server/mod.rs
- crates/shadowsocks/src/net/option.rs
- crates/shadowsocks/src/net/sys/unix/bsd/freebsd.rs
- crates/shadowsocks/src/net/sys/unix/bsd/macos.rs
- crates/shadowsocks/src/net/sys/unix/linux/mod.rs
- crates/shadowsocks/src/net/sys/windows/mod.rs
> Allow IP fragmentation for outbound UDP sockets

- crates/shadowsocks/src/net/udp.rs
This PR adds `UdpSocket::bind`, which is exactly `UdpSocket::bind_with_opts` with default `ConnectOpts`.
This adds a symmetry with the `UdpSocket::listen` and `UdpSocket::listen_with_opts` functions.
> Add `UdpSocket::bind`

- build/build-host-release.ps1
Change location inside powershell does not affect the working dir saw by .NET functions. Thus absolute path is needed.
> fix: file path in powershell script

- bin/sswinservice.rs
- src/error.rs
- src/lib.rs
- src/service/local.rs
- src/service/manager.rs
- src/service/server.rs
Hi! New contributor to this project here.
This PR refactors error handling in the local/manager/server binaries, resulting in a net reduction of 26 lines of code.
> refactor: change error handling to be strongly-typed

- .github/workflows/build-release.yml
- Cargo.lock
- Updated `moka` to `v0.12.10` by running `cargo update -p moka`.
- Reenable mips-* builds as `moka@v0.12.10` automatically switches to a fallback implementation for `AtomicU64` when necessary. (It uses [portable-atomic](https://crates.io/crates/portable-atomic) crate)
https://github.com/moka-rs/moka/blob/main/CHANGELOG.md#version-01210
Tested locally by running the following command and confirming that the build succeeded:
```console
$ cross +nightly build --target mips-unknown-linux-gnu -Z build-std=std,panic_abort,proc_macro
```
> fix: mips-* reenabled, moka automatically switches to a fallback impl for AtomicU64

- crates/shadowsocks/src/net/sys/unix/linux/mod.rs
`std::io::ErrorKind` is imported twice for android build.
> fix: fixed build on android

- Cargo.toml
`hickory-dns` is enabled by default even using `--no-default-features`, though it is specified as optional in README.
> fix: make hickory-dns truly optional

- crates/shadowsocks-service/src/manager/server.rs
#1968 made it possible to actually disable `aead-cipher` feature for `shadowsocks-service`.
That exposed previously unreachable code path which does not compile.
Closes #1982.
> fix(shadowsocks-service): fix compilation without `aead-cipher`

- crates/shadowsocks-service/src/acl/mod.rs
https://blog.rust-lang.org/2025/08/07/Rust-1.89.0/#mismatched-lifetime-syntaxes-lint
```
warning: hiding a lifetime that's elided elsewhere is confusing
--> crates/shadowsocks-service/src/acl/mod.rs:546:31
|
546 |     fn convert_to_ascii(host: &str) -> Cow<str> {
|                               ^^^^     -------- the same lifetime is hidden here
|                               |
|                               the lifetime is elided here
|
= help: the same lifetime is referred to in inconsistent ways, making the signature confusing
= note: `#[warn(mismatched_lifetime_syntaxes)]` on by default
help: use `'_` for type paths
|
546 |     fn convert_to_ascii(host: &str) -> Cow<'_, str> {
|                                            +++
warning: `shadowsocks-service` (lib) generated 1 warning …
```
> chore: mismatched_lifetime_syntaxes warning

- Dockerfile
Improvements:
- don't install unnecessary packages
- use toolchain from base image (drop command `rustup override set stable`)
I also tried to drop dependency on musl-cross (musl.cc) by using QEMU emulation but build time increased from 30 to 70 minutes. Not great but I can make a PR if anyone interested.
> chore: refactor Docker image building

- Cargo.lock
- Cargo.toml
- README.md
- src/config.rs
- src/logging/mod.rs
- src/logging/tracing.rs
- src/service/local.rs
- src/service/manager.rs
- src/service/server.rs
This is the second attempt of https://github.com/shadowsocks/shadowsocks-rust/pull/1992, as requested in https://github.com/shadowsocks/shadowsocks-rust/issues/1990#issuecomment-3122188623
Compare to the first attempt, this iteration enables more flexibility for logging configuration, supporting logging to stdout and multiple files simultaneously, which was a limitation in the previous version.
This new PR is intended as an alternative to the first iteration, feel free to close the other once decision is made.
---
I removed `SS*Config` structs as the amount of code duplication involved to deserialize the new `LogWriterConfig` enum is too much. And I don't really get the benefit of having them in the first place. I can see it makes sense for server configurations for backward compatibility …
> feat: file and advanced logging configuration for tracing
